### ISSUE TITLE
luarocks install is broken

### ISSUE THREAD

**Issue by kostja** [tarantool/curl#6]

**Comment by igorcoding** [comment]
Rockspec from in this and many other tarantool modules in https://github.com/tarantool (like avro-schema, mysql, pg, etc.) use build.type = 'cmake' which essentially does not cooperate with the default lua install paths. For example, installed module with build.type = 'builtin' has the following structure (luarocks install --tree=./libs http):
```
libs
├── lib
│   ├── lua
│   │   └── 5.1
│   │       └── http
│   │           └── lib.so
│   └── luarocks
│       └── rocks
│           ├── http
│           │   └── scm-1
│           │       ├── doc
│           │       │   ├── LICENSE
│           │       │   └── README.md
│           │       ├── http-scm-1.rockspec
│           │       └── rock_manifest
│           └── manifest
└── share
    └── lua
        └── 5.1
            └── http
                ├── client.lua
                ├── codes.lua
                ├── mime_types.lua
                └── server.lua

```

But installing this and other "cmake' modules results in the following structure of libs:
```
$ tree libs
libs
└── lib
    └── luarocks
        └── rocks
            ├── manifest
            └── tarantool-curl
                └── scm-1
                    ├── doc
                    │   ├── LICENSE
                    │   └── README.md
                    ├── rock_manifest
                    └── tarantool-curl-scm-1.rockspec

6 directories, 5 files
```

So, there are no actual tarantool-curl artifacts in this folder, because they have been installed to the default install path:
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/tarantool/curl/driver.so
-- Installing: /usr/local/share/tarantool/curl/init.lua
```

This fact has two effects:
1. `luarocks install` installs modules into the _system_ paths and not the path we passed (via `--tree=./libs`)
2. `luarocks remove <package>` does not remove the package, because it knows nothing about these default tarantool paths (like /usr/share/tarantool and /usr/lib/tarantool)

The problem is that FindTarantool.cmake defines these paths and it doesn't know anything about whether it is being installed through luarocks or not (so no information about install paths, which are defined with --tree=./libs or --local).

**Comment by knazarov** [comment]
It is fixable. See: https://github.com/tarantool/mysql/tree/switch-rockspec-to-cmake
